steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-nodejs-app', '.']

# Step 2: Push the Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-nodejs-app']

# Step 3: Deploy the Docker image to Google Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'my-nodejs-app'
  - '--image'
  - 'gcr.io/$PROJECT_ID/my-nodejs-app'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'