# Defaults

name: "hpa-app-k8s-test"
project_id: ""
replicasCount: 2
maxReplicaCount: 10
version: "latest"
resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 25m
    memory: 32Mi