# Defaults

name: "hpa-app-k8s-test"
project_id: ""
replicasCount: 1
maxReplicaCount: 10
version: "latest"
resources:
  limits:
    cpu: 100m
    memory: 126Mi
  requests:
    cpu: 25m
    memory: 32Mi