apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}"
spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      app: "{{ .Values.name }}-app"
      scope: test
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}-app"
        scope: test
    spec:
      containers:
      - name: hpa-autoscale-poc
        image: "gcr.io/{{ .Values.project_id }}/{{ .Values.name }}:{{ .Values.version }}"
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          limits:
            cpu: "{{ .Values.resources.limits.cpu }}"
            memory: "{{ .Values.resources.limits.memory }}"
          requests:
            cpu: "{{ .Values.resources.requests.cpu }}"
            memory: "{{ .Values.resources.requests.memory }}"