apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Values.name }}"
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 30
        type: Percent
        value: 30
      selectPolicy: Max
      stabilizationWindowSeconds: 20
    scaleUp:
      policies:
      - periodSeconds: 15
        type: Pods
        value: 2
      - periodSeconds: 15
        type: Percent
        value: 60
      selectPolicy: Max
      stabilizationWindowSeconds: 20
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .Values.name }}"
  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: {{ .Values.maxReplicaCount }}