apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}-service"
spec:
  type: NodePort
  selector:
    app: "{{ .Values.name }}-app"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000